/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        High: 72
        Low: 51
        Never saw temperature: 63
        Never saw temperature: 67
        Never saw temperature: 68
        Never saw temperature: 69
    }
}
