/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

public class App {
    HashSet<Integer> uniqueTemp = new HashSet<>();
    int[][] weeklyMonthTemperatures = {
            {66, 64, 58, 65, 71, 57, 60},
            {57, 65, 65, 70, 72, 65, 51},
            {55, 54, 60, 53, 59, 57, 61},
            {65, 56, 55, 52, 55, 62, 57}
    };
}
