/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test public void testRollTheDice(){
        Roll classUnderTest = new Roll();
        int[] outputArray = classUnderTest.RollTheDice(n, n)
        int[] expectedOutcome = {n}
    }
}
