/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public class Roll{
        public int[] RollTheDice{
            int numbers = Math.random() * 6;
            make an array 
            for(int i = 0; i < )
            put that number into the array
            use a for loop to put those numbers into an array
            display that array, with the number of rolls(counter)
        }
    }
}


initialize the array 
int[] numbers = new int[5]
must define the number of indices in the array.